config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD

  devise_for :users
  resources :listings do
  	resources :orders
  end

=======
  devise_for :users
  resources :listings
>>>>>>> cc08a7159a10574456274d0f7004051b9c917efd

  get 'pages/about'

  get 'pages/contact'

  get 'seller' => "listings#seller"

  root 'listings#index'

  
end

app/models/listing.rb
class Listing < ActiveRecord::Base
	if Rails.env.development?
		has_attached_file :image, :styles => { :medium => "200x200", :thumb => "100x100>" }, :default_url => "default.png"
	else
		has_attached_file :image, :styles => { :medium => "200x200", :thumb => "100x100>" }, :default_url => "default.png",
					  	  :storage => :dropbox,
					      :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
					      :path => ":style/:id_:filename"
	end		  
					validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
					validates :name, :description, :price, presence: true
					validates :price, numericality: { greater_than: 0 }
					validates_attachment_presence :image

					belongs_to :user
<<<<<<< HEAD
					has_many :orders
=======
>>>>>>> cc08a7159a10574456274d0f7004051b9c917efd
end

app/models/order.rb
class Order < ActiveRecord::Base
	validates :address, :city, :state, presence: true
	belongs_to :listing
	belongs_to :buyer, class_name: "User"
	belongs_to :seller, class_name: "User" 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  has_many :listings, dependent: :destroy
<<<<<<< HEAD
  has_many :sales, class_name: "Order", foreign_key: "seller_id"
  has_many :purchases, class_name: "Order", foreign_key: "buyer_id"
=======
>>>>>>> cc08a7159a10574456274d0f7004051b9c917efd
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:seller, :new, :create, :edit, :update, :destroy]
  before_filter :check_user, only: [:edit, :update, :destroy]

  def seller
    @listings = Listing.where(user: current_user).order("created_at DESC")
  end

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all.order("created_at DESC")
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price, :image)
    end

    def check_user
      if current_user != @listing.user
        redirect_to root_url, alert: "Sorry, this listing belongs to someone else"
      end
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  respond_to :html

  def index
    @orders = Order.all
    respond_with(@orders)
  end

  def show
    respond_with(@order)
  end

  def new
    @order = Order.new
    @listing = Listing.find(params[:listing_id])
    respond_with(@order)
  end

  def edit
  end

  def create
    @order = Order.new(order_params)
    @listing = Listing.find(params[:listing_id])
    @seller = @listing.user

    @order.listing_id = @listing.id
    @order.buyer_id = current_user.id
    @order.seller_id = @seller.id
    
    respond_to do |format| 
      if @order.save 
        format.html { redirect_to root_url, notice: "Thanks for ordering!" } 
        format.json { render action: 'show', status: :created, location: @order } 
      else 
        format.html { render action: 'new' } 
        format.json { render json: @order.errors, status: :unprocessable_entity } 
      end 
    end
  end

  def update
    @order.update(order_params)
    respond_with(@order)
  end

  def destroy
    @order.destroy
    respond_with(@order)
  end

  private
  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:address, :city, :state)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count, resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
	<p>&copy; 2015 All Rights Reserved.</p>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Ski Share</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "About", pages_about_path %></li>
          <li><%= link_to "Contact", pages_contact_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li><%= link_to "Manage Listings", seller_path %></li>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
	<title>Ski Share</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
<<<<<<< HEAD

=======
>>>>>>> cc08a7159a10574456274d0f7004051b9c917efd
    </head>
    <body>

     <%= render 'layouts/header' %>

     <div class="container-fluid">

        <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name.to_s == "notice" ? "success" : "danger" %> alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
        <% end %>
        <% end %>

        <%= yield %>

        <%= render 'layouts/footer' %>

    </div>

  </body>
  </html>

app/views/listings/_form.html.erb
<div class="container">
  <%= form_for @listing, :html => { :multipart => true } do |f| %>
  <% if @listing.errors.any? %>
    <div class="alert alert-danger alert-dismissable" id="error_explanation">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h4>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/listings/edit.html.erb
<div class="container">
	<h1>Editing listing</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @listing, class: "btn btn-link" %> |
	<%= link_to 'Back', listings_path, class: "btn btn-link" %>
</div>

app/views/listings/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Header for Home Page Banner</h1>
    <h2>Sub heading for home page.</h2>
  </div>
</div>
<div class="container">
  <h1>Listings</h1>

  <% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-link" %>
  <% end %>

  <br>

  <div class="row">
    <% @listings.each do |listing| %>
<<<<<<< HEAD
    <div class="col-md-3 col-sm-4">
      <div class="thumbnail" data-mh="listings">
=======
    <div class="col-md-3">
      <div class="thumbnail">
>>>>>>> cc08a7159a10574456274d0f7004051b9c917efd
        <%= link_to image_tag(listing.image.url(:medium)), listing %>
        <div class="caption text-center">
          <h3><%= listing.name %></h3>
          <p><%= number_to_currency(listing.price) %></p>
<<<<<<< HEAD
          <p><%= "Sold By #{listing.user.name}" %></p>
=======
          <p><%= "Sold by #{listing.user.name}" %></p>
>>>>>>> cc08a7159a10574456274d0f7004051b9c917efd
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/listings/new.html.erb
<div class="container">
	<h1>New listing</h1>

	<%= render 'form' %>

	<%= link_to 'Back', listings_path, class: "btn btn-link" %>
</div>

app/views/listings/seller.html.erb
<div class="container">
  <% if user_signed_in? %>
  <%= link_to "New Listing", new_listing_path, class: "btn btn-primary" %>
  <% end %>

  <table class="table table-striped table-bordered">
    <tr>
      <th class="text-center">Image</th>
      <th class="text-center">Name</th>
      <th class="text-center">Description</th>
      <th class="text-center">Price</th>
      <th class="text-center">Actions</th>
    </tr>
    <% @listings.each do |listing| %>
    <tr>
      <td><%= image_tag listing.image.url(:thumb) %></td>
      <td><%= listing.name %></td>
      <td><%= listing.description %></td>
      <td><%= number_to_currency(listing.price) %></td>
      <td>
        <div class="btn-group">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            Action <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "View", listing, class: "btn btn-link" %></li>
            <li><%= link_to "Edit", edit_listing_path(listing), class: "btn btn-link" %></li>
            <li><%= link_to 'Delete', listing, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-link" %></li>
          </ul>
        </div>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/listings/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-3">
			<div class="thumbnail">
				<%= image_tag @listing.image.url(:medium) %>
			</div>
		</div>
		<div class="col-md-9">
			<h3><%= @listing.name %></h3>
			<p><%= number_to_currency(@listing.price) %></p>
			<p><%= @listing.description %></p>
<<<<<<< HEAD
			<%= link_to "Buy It Now", new_listing_order_path(@listing), class: "btn btn-primary" %>
=======
>>>>>>> cc08a7159a10574456274d0f7004051b9c917efd
		</div>
	</div>

	<% if current_user == @listing.user %>
<<<<<<< HEAD
	<%= link_to 'Edit', edit_listing_path(@listing), class: " btn btn-link" %> |
=======
	<%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-link" %> |
>>>>>>> cc08a7159a10574456274d0f7004051b9c917efd
	<% end %>
	<%= link_to 'Back', listings_path, class: "btn btn-link" %>
</div>

app/views/orders/_form.html.erb
<div class="container">
  <%= form_for([@listing, @order]) do |f| %>
  <% if @order.errors.any? %>
  <div class="alert alert-danger alert-dismissable" id="error_explanation">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <h4><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h4>

    <ul>
      <% @order.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :city %><br>
    <%= f.text_field :city, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :state %><br>
    <%= f.text_field :state, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Complete Order", class: "btn btn-success" %>
  </div>
  <% end %>
</div>

app/views/orders/edit.html.erb
<div class="container">
	<h1>Editing order</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @order %> |
	<%= link_to 'Back', orders_path %>
</div>

app/views/orders/index.html.erb
<div class="container">
  <h1>Listing orders</h1>

  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Address</th>
        <th>City</th>
        <th>State</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @orders.each do |order| %>
      <tr>
        <td><%= order.address %></td>
        <td><%= order.city %></td>
        <td><%= order.state %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Order', new_order_path %>
</div>

app/views/orders/new.html.erb
<div class="container">
	<h1>New order</h1>

	<%= render 'form' %>

	<%= link_to 'Back', listing_orders_path %>
</div>

app/views/orders/show.html.erb
<div class="container">
	<p id="notice"><%= notice %></p>

	<p>
		<strong>Address:</strong>
		<%= @order.address %>
	</p>

	<p>
		<strong>City:</strong>
		<%= @order.city %>
	</p>

	<p>
		<strong>State:</strong>
		<%= @order.state %>
	</p>

	<%= link_to 'Edit', edit_order_path(@order) %> |
	<%= link_to 'Back', orders_path %>
</div>

app/views/pages/about.html.erb
<div class="container">
	<h1>Welcome to Ski Share!</h1>
</div>

app/views/pages/contact.html.erb
<div class="container">
	<h1>Email us at info@skishareut.com</h1>
	<p>Ski Share is an online marketplace for buying, selling and renting snow gear and other goods.</p>
</div>